name: Build 

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - '../../src/**'

jobs:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g bats
    
