name: awsamplify-github-actions
run-name: ${{ github.actor }} is running GitHub Actions
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'src/**'
jobs:
  check-awsamplify-version:
    runs-on: ubuntu-latest
    steps:
      - name: set the aws 
        run: |
          echo "AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=YOUR_SECRET_ACCESS_KEY" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: install, build and test
        run: |
          npm install
          npm install -g @aws-amplify/cli
          # build and test
          # npm run build
          # npm run test
    
      - name: deploy
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: publish
          amplify_env: dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
